import os
from pathlib import Path
from dotenv import load_dotenv
from groq import Groq
from sentence_transformers import SentenceTransformer
from qdrant_client import QdrantClient
from qdrant_client.models import PointStruct, VectorParams, Distance
from langchain_text_splitters import (
    RecursiveCharacterTextSplitter,
    CharacterTextSplitter,
)
from langchain_community.document_loaders import TextLoader

load_dotenv()

api_key = os.getenv("API_KEY")
qdrant_api_key = os.getenv("QDRANT_API_KEY")
qdrant_endpoint = os.getenv("QDRANT_END_POINT")

if not api_key:
    raise ValueError("Sorry Invalid API KEY")

if not qdrant_api_key:
    raise ValueError("Sorry Invalid QDRANT API KEY")

if not qdrant_endpoint:
    raise ValueError("Sorry Invalid QDRANT ENDPOINT")


# Connect to Qdrant vector database
client_db = QdrantClient(
    url=qdrant_endpoint,
    api_key=qdrant_api_key,
)

# connect to Groq LLM
client_llm = Groq(api_key=api_key)


# Initialize the SentenceTransformer model for embeddings
model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)  # Transforms your text into 384-dimensional embeddings

# Initialize the LLM model for generating responses
llm_model = "openai/gpt-oss-120b"

collection_name = "rag_collection"
embedding_size = 384  # Dimension of the embeddings generated by the model

# Check if the collection already exists, and delete it if it does
if client_db.collection_exists(collection_name):
    print(f"Collection '{collection_name}' already exists.")
    client_db.delete_collection(collection_name)

# Create the collection with the specified vector parameters
client_db.create_collection(
    collection_name=collection_name,
    vectors_config=VectorParams(size=embedding_size, distance=Distance.COSINE),
)

# loading the text file into a single documents variable
loader = TextLoader("data/basic_dataset.txt", encoding="utf-8")

documents = loader.load()


# Split the documents into smaller chunks
splitter = CharacterTextSplitter(
    separator="\n\n",
    chunk_size=500,
    chunk_overlap=50,
)

# creating chunks of the documents
chunks = splitter.split_documents(documents)

# make a list of this chunks
texts = [chunk.page_content for chunk in chunks]

# embedded this list of chunks
embeddings = model.encode(texts)


# Create Qdrant points
points = []

for i, (chunk, embedding) in enumerate(zip(chunks, embeddings)):
    points.append(
        PointStruct(
            id=i,
            vector=embedding.tolist(),
            payload={
                "text": chunk.page_content,
            },
        )
    )


# upload point to qdrant vector db
client_db.upsert(
    collection_name=collection_name,
    points=points,
)


# searching the vector database for the most relevant embedding chunks based on a query
def search_documents(query, top_k=3):

    query_vector = model.encode(query).tolist()

    results = client_db.query_points(
        collection_name=collection_name,
        query=query_vector,
        limit=top_k,
        with_payload=True,
    )

    return results.points


# Generate a response using the most relevant documents from the vector database
def ask_llm(query, context):
    SYSTEM_PROMPT = """
    You are a Linux operating system assistant.

    Your job is to answer questions related to:
    - Linux commands
    - Linux concepts
    - Linux files and directories
    - Linux permissions
    - Linux processes
    - Linux networking
    - Linux package management
    - Linux troubleshooting
    - Linux system administration

    If the user's question is unrelated to Linux or the Linux operating system,
    reply exactly:

    I only answer questions about the Linux operating system and related topics.

    Use the provided context to answer the question.
    If the context does not contain enough information, clearly say that you
    do not have enough information instead of inventing an answer.

    Keep answers beginner-friendly and explain commands when useful.
    """
    prompt = f"""
    You are a helpful assistant. Use the following context to answer the question.
    Context: {context}
    Question: {query}
    if you don't know the answer, just say "I don't know". Do not try to make up an answer.
    """
    response = client_llm.chat.completions.create(
        model=llm_model,
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },
            {"role": "user", "content": prompt},
        ],
    )

    return response.choices[0].message.content.strip()


print("Enter your linux query: ")
query = input()

search_doc_results = search_documents(query, 1)

context = "\n".join(result.payload["text"] for result in search_doc_results)

answer = ask_llm(query, context)

print(f"Answer: {answer}")
